version: "3"

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: templatedb
      POSTGRES_USER: template-app-user
      POSTGRES_PASSWORD: template-app-password

  service:
    build: ./
    restart: always
    ports:
      - "9080:9080"
    depends_on:
      - postgres
    environment:
      DB_URL: 'jdbc:postgresql://postgres:5432/templatedb'
      DB_USER: template-app-user
      DB_PASSWORD: template-app-password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9080/health"]
      interval: 1m
      timeout: 10s
      retries: 3
