spring.application.name=Spring Boot 3 Template App

server.port=9080

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=never
management.endpoint.health.probes.enabled=true
info.app.name=${spring.application.name}
info.app.description=Template project for Spring Boot 3

# Uncomment to see generated queries to DB in logs
#spring.jpa.show-sql=true
