name: Pull request workflow
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    - name: Grant execute permission for mvnw
      run: chmod +x mvnw

    - name: Build with Maven wrapper
      run: ./mvnw -B package --file pom.xml
